#!/usr/bin/env bash
# script to report information about subdomains
# ignore shellcheck disable=SC2086
check_domain() {
	# awk will use record seperator of space
	# space sperated list of sub domain
	 line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}
if [ "$#" == 1 ]
then
  check_domain "$1" "www"
  check_domain "$1" "lb-01"
  check_domain "$1" "web-01"
  check_domain "$1" "web-02"
elif [ "$#" == 2 ]
then
  check_domain "$1" "$2"
fi
