#!/usr/bin/env bash
# Configures a new Ubuntu web-02 machine.
# Installs Nginx with the following configurations.
# Listens on port 80.

apt-get update
apt-get -y install nginx
sed -i "/server_name _;/a add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-available/default
service nginx restart
